### ISSUE TITLE
Unable to define two Gradle tasks of type GaugeTask

### ISSUE THREAD

**Issue by apoorvam** [manupsunny/gauge-gradle-plugin#10]
From Ramesh Baskarasubramanian,

More details here: [issue](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/getgauge/-L6-WA4auh0/pOLMJjZrAwAJ)

**Comment by manupsunny** [comment]
**Adding the original message:**

We are trying to use the Gradle-gauge plugin and Gradle wrapper to run the Gauge specs. Since we have two test environments, we have defined two custom tasks of type GaugeTask. Here is the task definitions from the build.gradle file.

```
task runTestsInDev(type: GaugeTask) {
    gauge {
        specsDir = 'specs'
        tags = '!cleanup'
        env = 'dev'
        additionalFlags = '--verbose'
    }
}

task runTestsInUAT(type: GaugeTask) {
    gauge {
        specsDir = 'specs'
        tags = '!cleanup'
        env = 'uat'
        additionalFlags = '--verbose'
    }
}
```

Since the "runTestsInUAT" task is defined last, this task makes the other task irrelevant. So even when we run ./gradlew runTestsInDev, Gradle always ends up running the second task (that runs against the UAT environment).

Are we missing something basic here? Is there a different way to define these two custom tasks? Appreciate any help.

Thanks,
Ramesh

**Comment by manupsunny** [comment]
Hi Ramesh,

Problem here is, you are setting the extension properties in the **configuration phase** which will run always. So each invocation is overriding the previous. The solution is to set it in the **execution phase**. You can use a `doFirst { ... }` block for that. Eg:

```
task runTestsInDev(type: GaugeTask) {
    doFirst {
        gauge {
            specsDir = 'specs'
            tags = '!cleanup'
            env = 'dev'
            additionalFlags = '--verbose'
        }
    }
}

task runTestsInUAT(type: GaugeTask) {
    doFirst {
        gauge {
            specsDir = 'specs'
            tags = '!cleanup'
            env = 'uat'
            additionalFlags = '--verbose'
        }
    }
}
```

**Comment by rameshbaskar** [comment]
Thanks much Manu for the help. This worked :-)
